# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-db-secret
type: Opaque
data:
  DB_HOST: {{ .Values.env.DB_HOST | b64enc | quote }}
  DB_USER: {{ .Values.env.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | b64enc | quote }}
